### ISSUE TITLE
New Exception in IntelliJ 2018

### ISSUE THREAD

**Issue by PERAGIT** [shlxue/MvnRunner#17]
Hello,  I had put the next 2 comments in a closed issue.  I am re-posting here.  Thank you in advance.

Hello,

Here is another exception after updating to vertion 0.4.3 on IntelliJ 2018.1

update failed for ActionGroup: Test file (Run current File with Maven)[Test file]: com.intellij.psi.impl.source.tree.PsiCommentImpl cannot be cast to com.intellij.psi.PsiClass
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.PsiCommentImpl cannot be cast to com.intellij.psi.PsiClass
at com.lightd.ideap.maven.execution.MavenModuleConfigurationProducer.isConfigurationFromContext(MavenModuleConfigurationProducer.java:82)
at com.lightd.ideap.maven.execution.MavenModuleConfigurationProducer.findExistingConfiguration(MavenModuleConfigurationProducer.java:61)
at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:175)
at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:112)
at com.intellij.execution.actions.PreferredProducerFind.findConfigurationFromContext(PreferredProducerFind.java:137)
at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:44)
at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:149)
at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:140)
at krasa.mavenhelper.action.RunTestFileAction.update(RunTestFileAction.java:192)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:259)
at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:336)
at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:310)
at com.intellij.openapi.actionSystem.impl.Utils.hasVisibleChildren(Utils.java:276)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:216)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:365)
at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:110)
at com.intellij.openapi.editor.impl.EditorImpl.invokePopupIfNeeded(EditorImpl.java:4560)
at com.intellij.openapi.editor.impl.EditorImpl.access$9500(EditorImpl.java:124)
at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3627)
at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3533)
at java.awt.Component.processMouseEvent(Component.java:6548)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
at java.awt.Component.processEvent(Component.java:6313)
at java.awt.Container.processEvent(Container.java:2237)
at java.awt.Component.dispatchEventImpl(Component.java:4903)
at java.awt.Container.dispatchEventImpl(Container.java:2295)
at java.awt.Component.dispatchEvent(Component.java:4725)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
at java.awt.Container.dispatchEventImpl(Container.java:2281)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4725)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
at java.awt.EventQueue.access$500(EventQueue.java:98)
at java.awt.EventQueue$3.run(EventQueue.java:715)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
at java.awt.EventQueue$4.run(EventQueue.java:737)
at java.awt.EventQueue$4.run(EventQueue.java:735)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:723)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by PERAGIT** [comment]
Pretty consistent - A slightly different exception:

update failed for ActionGroup: Test file (Run current File with Maven)[Test file]: com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl cannot be cast to com.intellij.psi.PsiClass
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl cannot be cast to com.intellij.psi.PsiClass
at com.lightd.ideap.maven.execution.MavenModuleConfigurationProducer.isConfigurationFromContext(MavenModuleConfigurationProducer.java:82)
at com.lightd.ideap.maven.execution.MavenModuleConfigurationProducer.findExistingConfiguration(MavenModuleConfigurationProducer.java:61)
at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:175)
at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:112)
at com.intellij.execution.actions.PreferredProducerFind.findConfigurationFromContext(PreferredProducerFind.java:137)
at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:44)
at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:149)
at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:140)
at krasa.mavenhelper.action.RunTestFileAction.update(RunTestFileAction.java:192)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:259)
at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:336)
at com.intellij.openapi.actionSystem.impl.Utils.hasChildrenWithState(Utils.java:310)
at com.intellij.openapi.actionSystem.impl.Utils.hasVisibleChildren(Utils.java:276)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:216)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:365)
at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:110)
at com.intellij.openapi.editor.impl.EditorImpl.invokePopupIfNeeded(EditorImpl.java:4560)
at com.intellij.openapi.editor.impl.EditorImpl.access$9500(EditorImpl.java:124)
at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3627)
at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3533)
at java.awt.Component.processMouseEvent(Component.java:6548)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
at java.awt.Component.processEvent(Component.java:6313)
at java.awt.Container.processEvent(Container.java:2237)
at java.awt.Component.dispatchEventImpl(Component.java:4903)
at java.awt.Container.dispatchEventImpl(Container.java:2295)
at java.awt.Component.dispatchEvent(Component.java:4725)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
at java.awt.Container.dispatchEventImpl(Container.java:2281)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4725)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
at java.awt.EventQueue.access$500(EventQueue.java:98)
at java.awt.EventQueue$3.run(EventQueue.java:715)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
at java.awt.EventQueue$4.run(EventQueue.java:737)
at java.awt.EventQueue$4.run(EventQueue.java:735)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:723)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by shlxue** [comment]
disable running test feature, and update version to 0.4.4.
