### ISSUE TITLE
Exception in Intellij

### ISSUE THREAD

**Issue by stevensouza** [shlxue/MvnRunner#22]
Thanks for your open source project.  

I am receiving the following stack trace.

com.intellij.diagnostic.PluginException: Icon cannot be found in 'MavenIcons.MavenLogo', action 'class com.lightd.ideap.maven.actions.MvnOpenPomAction' [Plugin: MvnRunner]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:390)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:385)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.setIconFromClass(ActionManagerImpl.java:302)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.updateIconFromStub(ActionManagerImpl.java:267)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:570)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:558)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:393)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
	at com.intellij.openapi.actionSystem.ActionGroupStub.initGroup(ActionGroupStub.kt:34)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertGroupStub(ActionManagerImpl.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:570)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:558)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:393)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:371)
	at com.intellij.openapi.actionSystem.ActionGroupStub.initGroup(ActionGroupStub.kt:34)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertGroupStub(ActionManagerImpl.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:570)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:558)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:393)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:331)
	at com.intellij.ide.ui.customization.CustomizationUtil.getReordableChildren(CustomizationUtil.java:67)
	at com.intellij.ide.ui.customization.CustomisedActionGroup.getChildren(CustomisedActionGroup.java:43)
	at com.intellij.openapi.wm.impl.IdeMenuBar.expandActionGroup(IdeMenuBar.java:466)
	at com.intellij.openapi.wm.impl.IdeMenuBar.doUpdateMenuActions(IdeMenuBar.java:371)
	at com.intellij.openapi.wm.impl.IdeMenuBar.lambda$addNotify$2(IdeMenuBar.java:275)
	at com.intellij.openapi.wm.impl.IdeMenuBar.lambda$doWithLazyActionManager$3(IdeMenuBar.java:288)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

**Comment by ravi005e** [comment]
using 
IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2042M
Cores: 8
Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.2)
    net.kenro.ji.jin.intellij.purescript (v0.53.1)
    indent-rainbow.indent-rainbow (2.0.2)
    com.unger1984.npmdependencychecker (0.0.3)
    com.tabnine.TabNine (0.6.0)
    tarn.gradle.dependencies (1.6)
    org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)
    com.zt.json-editor (2.9.1)
    com.intellij.guice (213.5744.125)
    com.github.ragurney.spotless (1.0.7)
    com.andrey4623.rainbowcsv (2.0.1)
    ch.newinstance.plugin.mavendependencychecker (1.3.1)
    YAML/Ansible support (0.11.2)
    com.intellij.selenium (213.5744.172)
    String Manipulation (9.4.0)
    Sexy Editor (2.1)
    HighlightBracketPair (1.3.4)
    mobi.hsz.idea.gitignore (4.4.0)
    io.pivotal.jasmine (1.8)
    org.zhangwenqing.wdio.idea-run-wdio (2021.9.24-0)
    me.mbolotov.cypress (1.4.2)
    CheckStyle-IDEA (5.64.0)
    CMD Support (1.0.5)
    Batch Scripts Support (1.0.13)
    ru.adelf.idea.dotenv (2022.1)
    com.nbadal.ktlint (0.9.0)
    com.github.developerutils.kotlin-function-arguments-helper (2021.3.0)
    name.tachenov.intellij.maven-dependency-updater (2021.3)
    de.dm.intellij.maven-archetypes-catalog-plugin (1.4.0)
    MavenRunHelper (4.20.213.3714.1)
    com.github.platan.gradle-dependencies-formatter (0.6.1)
    GradleDependenciesHelper (1.16)
    org.intellij.scala (2021.3.20)
    io.nimbly.tzatziki (11.1.7)

Kotlin: 213-1.6.10-release-923-IJ5744.223
